export const prompts = [
    "A pretty girl named Priyanka with curly hair and pretty eyes",
    "A futuristic city skyline at sunset with flying cars and neon lights",
    "A magical forest with glowing trees and mythical creatures",
    "A steampunk-inspired airship flying over a mountain range",
    "A surreal landscape with floating islands and waterfalls in the sky",
    // "A cozy winter cabin in the woods with smoke coming from the chimney",
    // "A majestic dragon soaring above a medieval castle",
    // "A peaceful beach scene at dawn with gentle waves and soft pastel colors",
    // "An astronaut floating in space with the Earth in the background",
    // "A vibrant underwater coral reef with diverse marine life",
    // "A sci-fi robot standing in a futuristic laboratory",
    // "A serene Japanese garden with cherry blossoms in full bloom",
    // "A bustling marketplace in an ancient Middle Eastern city",
    // "A dramatic thunderstorm over a vast desert landscape",
    // "A colorful hot air balloon festival in a wide open field",
    // "A mystical mountain range with a hidden temple at its peak",
    // "A futuristic cyberpunk city street at night with neon signs",
    // "A tranquil river flowing through a dense, misty forest",
    // "A cozy café in Paris with people sitting outside enjoying coffee",
    // "A snowy mountain peak under a clear, starry night sky",
    // "A fantasy castle floating in the clouds with rainbows surrounding it",
    // "A bustling futuristic metropolis with towering skyscrapers",
    // "A serene meadow with wildflowers and a gentle stream",
    // "An enchanted library filled with floating books and magical lights",
    // "A vibrant sunset over a tropical island with palm trees",
    // "A retro 80s arcade with neon lights and vintage game machines",
    // "A majestic lion standing on a rock overlooking the savannah",
    // "A mystical portal in the middle of an ancient forest",
    // "A dramatic sunset over the Grand Canyon with vivid colors",
    // "A futuristic space station orbiting a distant planet",
    // "A cozy autumn scene with falling leaves and a pumpkin patch",
    // "A medieval knight in shining armor standing in a battlefield",
    // "A serene lake surrounded by towering mountains at sunrise",
    // "A bustling ancient Roman marketplace with vendors and shoppers",
    // "A surreal desert landscape with giant sand dunes and mysterious ruins",
    // "A fantasy world with flying ships and floating cities",
    // "A tranquil Zen garden with carefully raked sand and stone lanterns",
    // "A bustling New York City street during the holiday season",
    // "A majestic eagle soaring above a mountain range",
    // "A futuristic laboratory with advanced technology and holograms",
    // "A peaceful village in the countryside with rolling hills and farms",
    // "A dramatic stormy sea with a ship struggling against the waves",
    // "A magical underwater city with glowing buildings and sea creatures",
    // "A cozy fireplace in a rustic cabin during a snowy evening",
    // "A bustling bazaar in an ancient Arabian city with colorful textiles",
    // "A serene beach with crystal-clear water and gentle waves",
    // "A futuristic car speeding through a neon-lit city at night",
    // "A fantasy forest with giant mushrooms and glowing plants",
    // "A majestic waterfall cascading down a lush green cliff",
    // "A peaceful sunset over a serene lake with birds flying in the distance"
];
